### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by matmerr** [MathewMerrick/Apple-Pong#4]
-Important-
Ball has no logic.

**Comment by MathewMerrick** [comment]
Touch input. add two on screen buttons

**Comment by matmerr** [comment]
The increment of ball.x and ball.y is based purely on how fast the CPU can repeat the loop after if the base case conditions are met. It would be moving wicked fast on a CPU with a high clock, or not-as-fast on a really old CPU. You could do a while loop with a Thread.Sleep(#ofMilliseconds) type route though.

Setting a timer does the same thing. If you were to set the timer to increment every say, 1.666ms, the ball would be traveling somewhere around a cool 60 fps. But then you have to think that each time around, that ball.x is being incremented ~60 times a second. If you were to increment ball.x += 1 every timer increment, it would take around ~18 seconds for the ball to travel the court. (Canvas Width) / (Frames per Second).
